cgwire/gazu

gazu/asset.py
My first (tiny) pull request for gazu !
=> Change route to fetch all assets to match zou route.

test/test_asset.py
Sorry for the delay. I'm pretty new at unit testing...
=> Test correction after changing asset route.

README.md
Guidelines for contributions are missing. I add here a link to the C4 protocol.
=> Add contribution guideline to the README

gazu/shot.py, test/test_shot.py
Previous route path for shots was `/data/shots`. It is now `/data/shots/all`. The client must be updated to match this new route.
=> Adapt all_shot function to last API changes

gazu/__init__.py, gazu/asset.py, gazu/client.py, gazu/exception.py, gazu/files.py, gazu/person.py, gazu/project.py, gazu/shot.py, gazu/sorting.py, gazu/task.py, test/test_asset.py, test/test_client.py, test/test_files.py, test/test_person.py, test/test_project.py, test/test_shot.py, test/test_task.py
* Adapt renamed routes
* Add features that match the new asset management routes
* Make a cleaner API
=> Adapt Gazu to Zou refactoring

gazu/__init__.py, gazu/asset.py, gazu/client.py, gazu/context.py, gazu/exception.py, gazu/files.py, gazu/project.py, gazu/shot.py, gazu/task.py, gazu/user.py, requirements.txt, test/test_asset.py, test/test_client.py, test/test_files.py, test/test_project.py, test/test_shot.py, test/test_task.py, test/test_user.py
See commit history for details.
=> Many improvements

gazu/__init__.py, gazu/client.py, gazu/context.py, gazu/exception.py, gazu/files.py, gazu/person.py, gazu/shot.py, gazu/task.py, gazu/user.py, test/test_client.py, test/test_files.py, test/test_person.py, test/test_shot.py, test/test_task.py
**Problems**
* There is no easy way to request scene data.
* There is no easy way to retrieve users information.
**Solutions**
* Add function similar to shot functions but for scenes
* Add a function to get current user information
* Add a function to retrieve a user name based on his desktop login
* Add a function to retrieve the user list of the studio without sensitive information
=> Add scene helpers and more

gazu/asset.py, tests/test_asset.py
**Problem**
Remove asset function hits the wrong route.
**Solution**
Use the right in order to fix the remove asset command.
=> Fix remove asset command

gazu/__init__.py, gazu/asset.py, gazu/cache.py, gazu/files.py, gazu/person.py, gazu/project.py, gazu/shot.py, gazu/task.py, gazu/user.py
**Problem**
Many requests return the same result. It slows down software using Gazu to make the same HTTP requests again and again. 
**Solution**
Add a configurable cache system to all high level functions of Gazu.
By default it is not enabled. Once enabled, you can disable cache on given functions and set expiration time too.
=> Add caching capabilities

gazu/shot.py, gazu/task.py, tests/test_shot.py, tests/test_task.py
**Problems**
* There is no clean way to create shot, scene, sequence or episodes.
* There is no clean way to get details for a single shot, scene, sequence or episode.
* There is no clean way to get details for a single task.
**Solutions**
Add missing helper functions to handle all these use cases.
=> Add helpers for shot and task data

gazu/__init__.py, gazu/asset.py, gazu/cache.py, gazu/client.py, gazu/context.py, gazu/files.py, gazu/shot.py, gazu/task.py, gazu/user.py, tests/test_asset.py, tests/test_cache.py, tests/test_client.py, tests/test_files.py, tests/test_project.py, tests/test_shot.py, tests/test_task.py
**Problems**
* Output types routes need to be up to date with recent API changes
* Shot creation is broken when frame in and frame out are given
* All cache cannot be cleared with a single command
**Solutions**
* Use new routes to manage output types
* Fix shot creation (remove cyclic reference)
* Add a clear all caches function
=> Various fixes and improvements

gazu/shot.py
**Problem**
* There is no way to get an sequence by name of a specific episode
**Solution**
* Add the possibility to optionnaly add an episode while looking for an episode by name
=> get_sequence_by_name can now get the episode specified

gazu/__init__.py, gazu/asset.py, gazu/client.py, gazu/files.py, gazu/helpers.py, gazu/person.py, gazu/project.py, gazu/scene.py, gazu/shot.py, gazu/task.py, gazu/user.py, tests/test_asset.py, tests/test_files.py, tests/test_helpers.py, tests/test_person.py, tests/test_scene.py, tests/test_shot.py, tests/test_task.py
**Problems**
* There is no explicit way to retrieve presence logs.
* There is no explicit way to managen shot and layout scene links
**Solutions**
* Add a function to download the CSV file of presence logs.
* Add functions to link a shot to a list and retrieve shot and layout scene links.
=> Add some helpers

gazu/task.py
**Problem**
It is not possible to ask a review without changing status.
**Solution**
Add the chnange status flag to the to_review function.
=> Add change status flag to to review function

gazu/__init__.py, gazu/asset.py, gazu/events.py, gazu/shot.py, requirements.txt, tests/test_asset.py, tests/test_shot.py
**Problem**
* There is no way to instantiate an asset in another asset (like props in an environment)
* There is no way to listen to the API events
* `requests` version is outdated
**Solution**
* Add functions to access to creation and listing of asset asset instance
* Add a events api to add listener and to run a listener
* Up `requests` version
=> Event handler and asset asset instances

gazu/asset.py, gazu/person.py
**Problem**
* It is not possible to set desktop login field when creating a person
* There is no helper function to retrieve assets for a given episode
**Solution**
* Add desktop login field to person creation 
* Add missing helper function
=> Various improvements

gazu/task.py, gazu/user.py
* Add get to do list function
* Add get task status by short name
* Add remove task status function
=> Add helpers

gazu/playlist.py
The playlist module contains generic functions to retrieve or
interact with informations relatives to playlists in Kitsu.
=> Add playlist module

gazu/asset.py, gazu/cache.py, gazu/client.py, gazu/entity.py, gazu/events.py, gazu/files.py, gazu/helpers.py, gazu/person.py, gazu/project.py, gazu/shot.py, gazu/sorting.py, gazu/task.py, gazu/user.py, tests/test_person.py, tests/test_shot.py
**Problem**
Docstrings are not properly formatted. The consequence is that documentation generation is not clean.
**Solution**
Format all docstrings with Google format.
=> Turn all docstrings in Google format

gazu/shot.py, tests/test_shot.py
**Problem**
`get_shot_by_name` and `get_sequence_by_name` functoins lead to server errors.
**Solution**
Use the right parameters to retrieve shots and sequences by name.
=> Fix shot querying

gazu/__init__.py, gazu/asset.py, gazu/project.py, gazu/shot.py, tests/test_asset.py, tests/test_project.py, tests/test_shot.py
**Problem**
There is no explicit function to remove a given asset, shot, sequence, episode or project.
**Solution**
Add missing functions in `shot`, `project` and `asset` modules.
=> Add remove helpers

gazu/project.py
**Problem**
There is no way to update the data on an existing project.
**Solution**
Inspired by the methods for updating the shots, the code has been modified to update all project data and not just the metadata.
=> Update project methods inspired by shot updating.

gazu/task.py, tests/test_task.py
**Problem**
There was no method to assign a user to a task 
**Solution**
Added a method to do that.
=> added method gazu.task.assign_task

gazu/project.py
**Problem**
Need to retrieve all entity types of a project in one call.
**Solution**
Add a function in project module using client.fetch_one with entity-types parameter and passing an empty string as fetch id.
=> Added function to retrieve all entity types of a project

gazu/shot.py
**Problem**
- There is no way to get the list of previews for a given shot
**Solution**
- Added function all_previews_for_shot() that gives the list of all previews by task for the given shot
=> Added possibility to fetch all previews for a given shot

gazu/__init__.py, gazu/playlist.py
**Problem**
- Playlist functions where not loaded by Gazu
- all_playlist_for_project function was not using the right route
**Solution**
- Import the playlist functions when gazu is initalized
- fix the route for the all_playlist_for_project function
=> Added playlist functions to gazu

README.rst, gazu/task.py, tests/test_task.py
**Problem**
* No function to query the tasks by episode 
**Solution**
* Add functions `all_tasks_for_episode` and `all_task_types_for_episode`
=> Add episode tasks

gazu/client.py, gazu/files.py, tests/test_files.py, tests/test_person.py
adapt to route changes proposed in https://github.com/cgwire/zou/pull/182
=> New parameters in get_last_output_files_* methods

gazu/entity.py, gazu/task.py, tests/test_entity.py, tests/test_task.py
**Problem**
- no method to retrieve all entities
- no method to create an entity type
- no method to create a task type
- no method to create a task status
**Solution**
add methods for all.
=> add new methods for entities and tasks

gazu/cache.py, gazu/context.py, gazu/entity.py, gazu/files.py, gazu/helpers.py, gazu/scene.py, gazu/shot.py, gazu/task.py
- More generic type testing (works with unicode and OrderedDict)
- set all cache to expire after 2 minutes
- fix all_sequences_for_project + pep8
- normalize params
- add method for entities
=> Add methods for entities and set default cache timeout to 2 minutes

gazu/person.py
**Problem**
Misleading discrepancy in the docsting of `get_person`
**Solution**
Rewrite docstring
=> Fix argument in docstring

gazu/context.py, gazu/user.py, tests/test_user.py
**Problem**
There were no functions to get the tasks/task types for a sequence and the current user.
**Solution**
I added those functions.
=> Added functions to get tasks and task types for user and sequence.

gazu/__init__.py, gazu/casting.py, gazu/entity.py, gazu/files.py, gazu/helpers.py, gazu/shot.py, gazu/task.py, tests/test_asset.py, tests/test_casting.py, tests/test_entity.py, tests/test_files.py, tests/test_helpers.py, tests/test_scene.py, tests/test_shot.py, tests/test_task.py, tests/test_user.py, tests/utils.py
**Problem**
There are no explicit functions to take advantage of the casting API.
**Solution**
Add the missing functions:
* `update_shot_casting`
* `update_asset_casting`
* `get_asset_type_casting`
* `get_sequence_casting`
* `get_shot_casting`
* `get_asset_casting`
* `get_asset_cast_in`
=> Add casting functions

gazu/project.py
**Problem**
* It's not possible to force project deletion with Gazu.
**Solution**
* Add a force flag to remove project function.
=> Allow to force project deletion

gazu/asset.py, gazu/casting.py, tests/test_casting.py
**Problem**
* Casting update functions don't work anymore.
* Asset creation function doesn't hande episode parameter properly.
**Solution**
* Use the new route scheme to update casting in casting functions.
* Use `episode_id` parameter to set the episode on assets.
=> Various fixes

gazu/task.py
**Problem**
Tasks and task data can not be updated.
**Solution**
Add functions to update task and task_data
=> Add update_task and update_task_data functions

gazu/shot.py
**Problem**
* It's not possible to update sequences via a proper fuction.
* It's not possible to set shot frames at shot creation.
**Solution**
* Add missing sequence methods.
* Allow to give a `nb_frames` parameter in shot creation function.
=> Add update sequences methods

gazu/shot.py
**Problem**
There was no method for updating episode data.
**Solution**
Added `update_episode_data` and `update_episode`, copied from `update_sequence_data` and `update_sequence`.
=> Add update_episode and update_episode_data

gazu/asset.py, gazu/shot.py
**Problem**
* Update a sequence raise an error if the data field doesn't exist.
* Create an asset linked to an episode does not work
**Solution**
* Test data before updating.
* Replace source_id by episode_id in data
=> Create asset linked to an episode.

gazu/client.py, gazu/files.py
**Problem**
The Python viewer needed to retrieve data (images, videos, etc) from the kistu server.
It also needed a getter for preview files.
**Solution**
A function was added to retrieve, given the appropriate url, the data located at this emplacement.
A getter for preview files was also added.
=> Add function for data retrieving from url and getter for preview files

gazu/files.py, tests/test_files.py
**Problem**
No possibility to create or retrieve file statuses
**Solution**
Add methods to create or retrieve file statuses
=> add the possibilty to create and retrieve file statuses

gazu/files.py
Problem
No possibility to filter output files using their file status
Solution
Add a file status parameter for methods retrieving output files
=> add a parameter to filter output files using file status

gazu/client.py
**Problem**
There is no function checking if a host is valid. The existing host_is_up function can return True sometimes, even if the host can not perform any login.
**Solution**
A function host_is_valid was added. It checks first if the host is up, then tries a fake login (id and password null), and checks if the returned error is the one we are waiting for (a BadPassword-like error)
=> Add host_is_valid function

gazu/client.py, gazu/task.py
**Problem**
* It is not possible to set a comment in a name of a given person.
* It is not possible to add attachments to the comment.
**Solution**
* Add the `person` parameter to `add_comment` function.
* Add an `attachment` parameter to `add_comment` function. Improve `upload` function to add support for parameters and extra files.
=> Improve comment posting

gazu/asset.py, gazu/client.py, gazu/person.py, gazu/project.py, gazu/shot.py, gazu/task.py
**Problem**
The url associated with the different entities (project, asset, shot, etc...) are not easily accessible.
**Solution**
Added different functions enabling to get these urls.
Also added a function to retrieve Zou url from host.
=> [NEW] Add functions to retrieve url

docs/source/publisher.md
Fix a wrong instruction and some typo in the gazu publisher installation procedure
=> [FIX] Fix instructions in publisher installation

gazu/exception.py
**Problem**
A custom exception dedicated to a bad host when might be useful
**Solution**
This PR adds this exception.
=> Add host not valid exception

gazu/person.py
**Problem**
There was no function to retrieve the current organization.
**Solution**
The corresponding function was added.
=> Add a function to retrieve current organisation

gazu/files.py, gazu/scene.py, gazu/task.py
=> add some missing client kwargs

gazu/__init__.py
**Problem**
no log_out function
**Solution**
added a logout function that Log user out by revoking his auth tokens
=> added log_out function

gazu/playlist.py
**Problem**
* There is no function to retrieve all playlists for an episode.
* The get playlist by name function doesn't work anymore.
**Solution**
* Add `all_playlist_for_episode` function.
* Use server parameters to retrieve a playlist via its name instead of listing them all.
* Add pagination parameter to `all_playlists_for_project` function.
=> [playlists] Improve playlists functions

README.rst, gazu/shot.py
**Problem**
There is no helper function to restore a shot that has been canceled.
**Solution**
Add a function to facilitate canceled shot restoration.
=> Add restore shot function

gazu/user.py, requirements.txt, tests/test_user.py
**Problem**
Some requirements are outdated.
No function to check if the current user is authenticated.
https://github.com/cgwire/gazu/issues/195
**Solution**
Upgrade outdated requirements.
Create new function to check if current user is authenticated and the tests for this function.
=> Upgrade requirements + add is_authenticated function

gazu/events.py, requirements.txt
**Problem**
socketio-client is buggy and not maintened anymore
https://github.com/cgwire/gazu/issues/194
**Solution**
use python-socketio[client] instead
=> use python-socketio instead of socketio-client

.travis.yml, .vscode/launch.json, requirements_test.txt, setup.cfg
**Problem**
Bidict>=0.21 not found for python2.7
No vscode conf for single file debugging
**Solution**
Set a good version of python-socketio for python2.7 (the module that needs bidict)
=> Fix for requirements in python 2.7

gazu/files.py
Missing functions:
- Download function for covers (original preview files in guaranteed image format)
- Download function for person avatars
- Download function for project avatars
=> Downloads for avatars and full size covers

gazu/files.py, gazu/project.py, tests/test_files.py
**Problem**
- some variables names are not correct
- some tests are missing
**Solution**
- rename some variables
- add missing tests
=> Best variable names + tests for new functions in files

gazu/client.py
**Problem**
This is not possible to specify a custom cert in create_client
**Solution**
Add this possibility
=> [client] add the possibility to specify a custom cert in create_client

gazu/client.py, gazu/entity.py, tests/test_entity.py
**Problem**
- the docstring for gazu.client.delete is wrong
- there's no function to remove an entity
**Solution**
- change the doctstring for gazu.client.delete
- add a function to delete an entity (gazu.entity.remove_entity) + tests
=> various commits

tests/test_files.py, tests/test_task.py
**Problem**
- missing tests for gazu.task.update_comment
**Solution**
- add tests for gazu.task.update_comment
=> [qa] add test for update_comment

docs/source/events.md
**Problem**
- the example for listening to events needs to be refactored to be logged in
**Solution**
- refactoring for the example
=> [events] update example for listining to events

gazu/helpers.py, tests/test_asset.py, tests/test_helpers.py, tests/test_person.py, tests/test_project.py, tests/test_shot.py, tests/test_task.py
**Problem**
- There's some functions that are not currently tested.
**Solution**
- Add some missing tests.
=> missing tests

setup.cfg, tests/test_client.py
**Problem**
- python 2 tests are broken due to black dependency
- refactoring
**Solution**
- remove black dependency for python 2 
- refactoring for tests/test_client.py
=> fix python 2 tests + refactoring

gazu/scene.py
**Problem**
`shot` instead of `scene`
**Solution**
Change variable name to `scene`
=> [qa] fix typo in scene.py

gazu/person.py
**Problem**
We wanted to get a full list of time spents for a given person and month.
**Solution**
We added the route to zou and added this function to easily access the route.
This is linked to [this PR in zou](https://github.com/cgwire/zou/pull/592).
=> feat: add gazu.person.get_all_month_time_spents function

gazu/entity.py
**Problem**
We needed a function to easily access the route added in [this zou PR](https://github.com/cgwire/zou/pull/603)
**Solution**
We added the function.
=> feat: add gazu.entity.guess_from_path function

gazu/person.py, gazu/user.py
**Problem**
We needed functions to access the new routes from [this zou PR](https://github.com/cgwire/zou/pull/602).
**Solution**
We added them.
=> feat: add functions to query timespents for specific date range

.pre-commit-config.yaml, .pre-commit-hooks.yaml, .travis.yml, gazu/__init__.py, gazu/cache.py, gazu/client.py, gazu/events.py, gazu/helpers.py, gazu/sync.py, gazu/task.py, setup.cfg, setup.py, tests/test_project.py, tests/utils.py
**Problem**
- We can easily re-add python 2 support for the API
**Solution**
- Re-add python 2 support but only for the API, not for the events
=> re-add python 2 support but not for events

gazu/__init__.py, gazu/asset.py, gazu/edit.py, gazu/shot.py, gazu/task.py, tests/test_edit.py, tests/test_shot.py
**Problem**
- There's no functions for edits 
**Solution**
- Add some functions for edits + related tests
=> [edit] add some functions + tests

gazu/task.py
**Problem**
The publish function has the wrong documentation and doesn't return the expected elements.
**Solution**
* Return all elements created
* Fix documentation
* Add a flag to set the preview as a thumbnail after the publishing
=> [task] Improve the publish function

setup.cfg
**Problem**
- some libs are outdated.
**Solution**
- upgrade outdated libs.
=> [requirements] upgrade some libs

RELEASE.md, scripts/release.sh
**Problem**
- We need to update the script for doing a new release due to the new process.
- We need to update RELEASE.md due to the new process.
**Solution**
- Update the script for doing a new release due to the new process with GitHub Actions.
- Update RELEASE.md due to the new process with GitHub Actions.
=> new process for release

.github/workflows/ci.yml
**Problem**
- we don't use cache in ci workflow 
**Solution**
- use cache in ci workflow
=> [github-actions][ci] use cache with pip

.github/workflows/ci.yml, setup.cfg
**Problem**
- We need to support and test python 3.12 (and all supported python versions)
**Solution**
- Test all versions supported 
- Inform that python 3.12 is supported
=> Python 3.12 support

requirements.txt
**Problem**
- We need to build documentation with the last version of Gazu.
**Solution**
- Use last version of Gazu.
=> [requirements] upgrade sphinx & gazu

.pre-commit-config.yaml, .pre-commit-hooks.yaml, gazu/exception.py, gazu/shot.py, gazu/task.py, setup.cfg, tests/test_client.py, tests/test_context.py, tests/test_edit.py, tests/test_project.py, tests/test_task.py
**Problem**
- Black
- There's no pre-commit for autoflake
- Some requirements are outdated
**Solution**
- Black
- Add pre-commit for autoflake + autoflake on every files
- Upgrade outdated requirements
=> qa: autflake, black, requirements

requirements.txt
**Problem**
Up Gazu version. 
**Solution**
Up Gazu version.
=> [requirements] upgrade gazu

gazu/client.py
**Problem**
Creating a pull request to run the check. (Last one had some type hinting left.)
=> More type hint removal for python 2.7

gazu/shot.py
Corrected the docstring for: 
all_sequences_for_project
all_sequences_for_episode
**Problem**
Docstring for the functions below was incorrect 
all_sequences_for_project
all_sequences_for_episode
**Solution**
corrected the arg requested in the docstring for both the functions.
=> Corrected docstring for 2 functions

gazu/shot.py, tests/test_shot.py, tests/test_user.py
**Problem**
The function `update_episode_data` is calling `get_sequence` with an episode id
**Solution**
Replace the use of `get_sequence` with `get_episode`
**Note**
The test `test_all_tasks_for_scene` was already failing before the changes
=> Fix the function udpate_episode_data
