.travis.yml
gazu/__init__.py
requirements.txt
requirements_test.txt
setup.py

**Problem**
The new configuration aimed at making the package publishable on Pypi breaks previous behaviour (install via git and gazu import). 
**Solution**
Come back to previous configuration until I find how to make a backward compatible migration.

Come back to previous configuration

---

gazu/asset.py
gazu/shot.py

**Problem**
- There was no function to update an asset
- There was not function to simply update the data dict of a shot or asset without deleting unprovided keys
**Solution**
- Create an update_asset function
- Create a specific function for both asset and shots that get the current data dict of the entity, update it with the provided values, and save it

adding update asset/shot data whitout deleting not provided keys

---

gazu/asset.py
gazu/context.py
gazu/files.py
gazu/scene.py
gazu/shot.py
gazu/task.py
tests/test_asset.py
tests/test_files.py
tests/test_scene.py
tests/test_shot.py

**Problem**
* Retreving asset, shot, scene, sequence or episode by name can lead to unexpected result (having a shot as result of getting an asset (#26)
* There is no function to retrieve a task type from its id
* Output files cannot be filtered on representation
**Solution**
* Use specific routes instead of generic one to get entities by name
* Add a function to get a task type from its id
* `all_output_files` functions allow to filter them on representation

Various improvements

---

README.rst
gazu/files.py
gazu/shot.py
gazu/task.py
tests/test_task.py

**Problem**
* Some function names does not match the way other function are named (all prefix, full name of requested concept).
* Gitter room is empty. Slack room has many users. It's sad the Slack badge is not displayed.
**Solution**
* Rename properly functions with wrong names.
* Change the Gitter badge to a Slack badge (Use a Slackin instance and related badge because there is no public access to Slack chatroom).

API improvements and Slackin badge

---

gazu/client.py
gazu/files.py
tests/test_files.py

**Problem**
* There is no simple way to update the project file tree.
* There is no method to download files from the api.
**Solution**
* Add missing method to the project module
* Add missing method to the raw client

Set project file tree and allow to download files

---

gazu/client.py

**Problem**
When an error occurs on server, the html error message is hard to read.
**Solution**
It prints a formated message when a request fails with a 500 status. It takes advantage of the new JSON formatting of server error implemented in the 0.9.1 version of Zou.

Better handling of server errors

---

README.rst

**Problem**
The Quickstart examples in the README did not work as expected.
**Solution**
Fix them. :)
- Add `/api` suffix to the host url.
- Update the list all open projects example code.

Fix README quickstart examples

---

README.rst
gazu/user.py

**Problem**
The example [`tasks = gazu.user.all_tasks_to_do()`](https://gazu.cg-wire.com/examples.html#get-user-todo-list) does not work.
The error is:
```python
>>> gazu.user.all_tasks_to_do()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Python27\lib\site-packages\gazu\cache.py", line 196, in wrapper
return function(*args, **kwargs)
File "C:\Python27\lib\site-packages\gazu\user.py", line 213, in all_tasks_to_do
return client.fetch_all("/data/users/tasks")
File "C:\Python27\lib\site-packages\gazu\client.py", line 239, in fetch_all
return get(url_path_join('data', path))
File "C:\Python27\lib\site-packages\gazu\client.py", line 119, in get
check_status(response, path)
File "C:\Python27\lib\site-packages\gazu\client.py", line 196, in check_status
raise …
```

Fix gazu.user.all_tasks_to_do() 

---

gazu/task.py

**Problem**
Probably a side effect of rebasing the Unit codebase, but we ended with some duplicate function definitions. 
**Solution**
Remove duplicates, keeping the functions with argument normalization and docstrings matching the rest of the code.

Remove duplicate function definitions

---

gazu/helpers.py
tests/test_asset.py
tests/test_cache.py
tests/test_client.py
tests/test_entity.py
tests/test_files.py
tests/test_helpers.py
tests/test_person.py
tests/test_project.py
tests/test_scene.py
tests/test_shot.py
tests/test_task.py
tests/test_user.py
tests/utils.py

**Problem**
In python 2, `normalize_model_parameter` raises an `ValueError` when the `id` it receives as an argument is a `unicode`
**Solution**
Test `id` type against `basestring` instead of `str`, which is the base type for `str` and `unicode` in python2 (using the `future` library for python3 compatibility).

Fix normalize_model_parameter to accept unicode arguments in python 2

---

gazu/person.py

**Problem**
The function `gazu.person.get_person` was broken since it relied on the removed function `gazu.client.fetch`.
**Solution**
Use `gazu.client.fetch_one` instead

Fix gazu.person.get_person

---

gazu/files.py

**Problem**
`get_all_working_files_for_entity` is broken, since the path it relies on get prepended with `"data/"` in the `client.fetch_all` function
**Solution**
Remove `"data/"` from the path string, and let `client.fetch_all` add it.

Fix path error

---

gazu/files.py

**Problem**
Some descriptions contain typing errors. And these have repercussions on the documentation.
**Solution**
I corrected the words in question.

files: replace fie by file in descriptions

---

gazu/scene.py

**Problem**
Could not create two instances of the same asset in a given scene without clearing the cache.
This lead to incomprehension.
**Solution**
Remove `cache` decorator from `new_scene_asset_instance` method.

remove cache from new_scene_asset_instance

---

gazu/asset.py

This PR replaces #92 
**Problem**
The `new_asset` function takes an `episode_id` parameter.
* Passing an `id` as a parameter is an old practice and violates homogeneity.
* The data field `episode_id` this value gets assigned to seems deprecated (no effect in kitsu)
**Solution**
* We normalize the `episode_id` parameter into a generic `episode` parameter (`dict` or `str`)
* We fix the data field this id is assigned to (used to be `episode_id`, now is `source_id`)

Fix `episode` parameter in `new_asset`

---

gazu/files.py
gazu/task.py

**Problem**
There is no way to handle a preview file between its creation and the upload of a file.
There is no way to handle a preview file data.
**Solution**
- Separate add_preview method in create_preview and upload_preview_file
to let the user add logic inbetweeen.
- Add update_preview method to update a preview file datas

Upgrade preview file handling methods

---

gazu/project.py

**Problem**
There was no easy way of closing a project.
**Solution**
Provide easy `close_project` method.
**Notes**
Not sure this is inline with gazu, but had to dig a bit to figure out how the project statuses worked, so I thought it might help someone else.

Add close_project method.

---

gazu/__init__.py
gazu/task.py
tests/test_task.py

**Problem**
See #107 
**Solution**
Use the new route available in Zou requiring only the preview as a parameter.

Simplify gazu.task.set_main_preview function

---

gazu/client.py

**Problem**
When a user enters a host manually, we need to check if this host is really up, but the function host_is_up throws errors. When its HEAD request fails, it returns the associated error message instead of a boolean. 
**Solution**
A try statement has been added to ensure the function always returns a boolean. The handling of the error is made higher in the code.

[NEW] Modify host_is_up function

---

gazu/task.py

**Problem**
`gazu.task.get_task_status(...)` does not accept a `task_id` as argument
**Solution**
Use the argument `normalize_model_parameter` function on the `task` parameter.
(improving global code consistency)

Fix missing parameter normalization

---

gazu/cache.py
tests/test_cache.py

**Problem**
There was no way to see the effectiveness of a cache
**Solution**
Add a method to display cache infos in a lru_cache way
```pyhon
gazu.person.all_persons.get_cache_infos()
>>> {'maxsize': 300, 'expire': 120, 'expired_hits': 0, 'misses': 0, 'current_size': 0, 'enabled': True, 'hits': 0}
all_1 = gazu.person.all_persons()
gazu.person.all_persons.get_cache_infos()
>>> {'maxsize': 300, 'expire': 120, 'expired_hits': 0, 'misses': 1, 'current_size': 0, 'enabled': True, 'hits': 0}
all_2 = gazu.person.all_persons()
gazu.person.all_persons.get_cache_infos()
>>> {'maxsize': 300, 'expire': 120, 'expired_hits': 0, 'misses': 1, 'current_size': 0, 'enabled': True, 'hits': 1}
```

add cache infos

---

gazu/files.py
tests/test_files.py

**Problem**
- file status was not possible to set at output file creation
- some params were malformed in output file creation requests
- sourcery messed the new_file_status test because of `**locals()`
**Solution**
- add a file_status_id param
- fix parmaters form
- do not use `**locals()`

Add file status id in output creation params

---

gazu/client.py

**Problem**
I have scratched my head around this traceback a long time : 
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\aboellinger\venv-gazu\lib\site-packages\gazu\task.py", line 610, in add_preview
upload_preview_file(preview_file, preview_file_path)
File "C:\Users\aboellinger\venv-gazu\lib\site-packages\gazu\task.py", line 594, in upload_preview_file
client.upload(path, file_path)
File "C:\Users\aboellinger\venv-gazu\lib\site-packages\gazu\client.py", line 316, in upload
url, headers=make_auth_header(), files=files
File "C:\Users\aboellinger\venv-gazu\lib\site-packages\requests\models.py", line 897, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\aboellinger\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", …
```

Fix obscure error message on error 413

---

gazu/__init__.py

**Problem**
When the user enters wrong ids, an unexpected error is displayed
**Solution**
Fix the bug : instead of being propagated, the login error was not treated

Fix uncaught error on login

---

gazu/task.py

**Problem**
New routes were created in https://github.com/cgwire/zou/blob/master/zou/app/blueprints/shots/__init__.py#L66
```("/data/episodes/<episode_id>/shot-tasks", EpisodeShotTasksResource)``` 
```("/data/sequences/<sequence_id>/shot-tasks", SequenceShotTasksResource)```
but not the necessary function to use them from gazu.
**Solution**
Add two functions to access those routes, following the same template already in place for others functions in the file.

feature(task api): add functions to access new routes sequences/id/shot-tasks and episodes/id/shot-tasks

---

gazu/files.py
tests/test_files.py

**Problem**
There is currently no function in the API to retrieve images attached to comments 
**Solution**
This PR adds this function, as well as the associated test.
Both of them are imitating the implementation of a similar function which downloads the thumbnail ([download_preview_file_thumbnail](https://github.com/LedruRollin/gazu/blob/dc3b1f2d35cd348e5f85e1ab944155a1007a9ba3/gazu/files.py#L1029) and [test_download_preview_file_thumbnail](https://github.com/LedruRollin/gazu/blob/dc3b1f2d35cd348e5f85e1ab944155a1007a9ba3/tests/test_files.py#L693))

Add fct to download attachment images of comments

---

gazu/__init__.py
gazu/asset.py
gazu/casting.py
gazu/client.py
gazu/entity.py
gazu/events.py
gazu/files.py
gazu/person.py
gazu/project.py
gazu/scene.py
gazu/shot.py
gazu/sync.py
gazu/task.py
gazu/user.py
tests/test_casting.py
tests/test_client.py
tests/test_task.py

**Problem**
* It is not possible to manage two hosts easily with Gazu. It makes things complicated when dealing with synchronisation.
* Some utilities would be nice to perform synchronizations.
**Solution**
* Add a client option to all functions. It allows us to instantiate a Kitsu client and pass it to functions call where targeting another host is needed. 
* A default client is given to all functions to not bring any breaking changes to Gazu.
* Add a function to create clients.
* Add functions to import data.
* Add functions to retrieve in a single request all tasks or links for a given project.
* Add diff functions to quickly build differential between two model lists.

Allow to have several instances of the gazu cilent

---

gazu/files.py
gazu/shot.py

using KitsuClient to call some gazu functions don't work.
the client is not used by the subcall.
patch:
gazu.files.get_output_file       => missing client kwargs calling raw.get
gazu.files.update_output_file => raw.put use client as arg (not kwarg)
gazu.shot.get_episode           => missing client kwargs calling raw.get
**Problem**
using a KitsuClient to call some functions don't work
=> issue discovered calling get_episode(episode_id, client=myKitsuClient)
**Solution**
=> make sure to pass the client to the subcall (raw.get, put, fetch_...)

patch missing client keyword argument

---

gazu/asset.py
gazu/project.py
gazu/shot.py
tests/test_asset.py
tests/test_client.py
tests/test_project.py
tests/test_shot.py

**Problem**
* It's not possible to give a simple ID to `get_asset_url` and `get_shot_url` functions.
* TV series are not supported by `get_asset_url` and `get_shot_url` functions.
* `get_episode_url` function is missing
**Solution**
* Retrieve data from server to build a proper Kitsu url.
* Handle TV series case when building urls (add episode parameter).
* Add missing function.

Url functions fixes

---

gazu/task.py
tests/test_task.py

⚠️ ⚠️ This PR breaks backward compatibility ⚠️ ⚠️ 
**Problem**
The method `get_task_status` is inconsistent with the other getters as it expects a `task` or `task_id`.
Not only this is inconsistent, but it also results in a huge performance bottleneck as it breaks the caching when you are getting statuses for a lot of tasks (see profiling screenshot below where `get_task_status` takes 90% of the execution time).
**Solution**
Change the expected argument for  `get_task_status` (to have it work like, for instance,  `get_task_type`).

Change get_task_status to match other getters specs

---

docs/source/examples.md

**Problem**
In the documentation examples, when retrieving a software, it was : 
```python
software = gazu.files.get_software(output_type_id)
```
**Solution**
It should use the software id instead : 
```python
software = gazu.files.get_software(software_id)
```

Fix output_type_id to software_id

---

docs/source/examples.md

**Problem**
Most of the examples about working with files were not up to date with the api functions (removed arguments and added new ones) : 
```python
gazu.files.build_working_file_path()
gazu.files.build_entity_output_file_path()
gazu.files.build_asset_instance_output_file_path()
```
**Solution**
For example, changed `version` to `revision`.

Fix files examples

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml
README.rst
requirements_test.txt

**Problem**
No pre-commit hook for black python code formatter
**Solution**
Add a pre-commit hook
To use it : 
`pip install pre-commit`
`pre-commit install`

[qa] Add pre-commit-hook for black python code formatter

---

gazu/__init__.py
gazu/asset.py
gazu/cache.py
gazu/client.py
gazu/context.py
gazu/entity.py
gazu/events.py
gazu/files.py
gazu/person.py
gazu/playlist.py
gazu/project.py
gazu/scene.py
gazu/shot.py
gazu/sync.py
gazu/task.py
pyproject.toml
tests/test_asset.py
tests/test_casting.py
tests/test_client.py
tests/test_context.py
tests/test_entity.py
tests/test_files.py
tests/test_person.py
tests/test_playlist.py
tests/test_project.py
tests/test_scene.py
tests/test_shot.py
tests/test_sync.py
tests/test_task.py
tests/test_user.py

**Problem**
Black python code formater was previously with line-length at 89. 
**Solution**
Pass black on every python files and set the line-length at 79 in a config file.

[qa] Black python code formater with line-length at 79

---

gazu/helpers.py
requirements_test.txt
tests/test_helpers.py
tests/test_task.py

**Problem**
Problem with the requirements_tests.txt for python2.7 and datetime.datetime has no attribute 'fromisoformat' in python < 3.7
**Solution**
Conditionnal requirements for python 2.7.
Remove the part with fromisoformat, it's useless because Zou doesn't use this for parsing date.

Travis not passing

---

.travis.yml
requirements.txt
setup.cfg
setup.py

**Problem**
After installing gazu in a clean environment through *pip*, we get an import error (see #198)
```(venv) C:\Users\aboellinger>python -c "import gazu"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\aboellinger\venv\lib\site-packages\gazu\__init__.py", line 4, in <module>
from . import events
File "C:\Users\aboellinger\venv\lib\site-packages\gazu\events.py", line 4, in <module>
import socketio
ModuleNotFoundError: No module named 'socketio'
```
**Solution**
- Having a single source of truth regarding dependencies (`setup.cfg`, with requirements.txt "referencing it" with `-e .`)
- Changes also introduced to `setup.py` to avoid importing gazu dependencies before we install them.

Fix requirements after socketio client refactoring.

---

.travis.yml
gazu/events.py
setup.cfg
setup.py

**Problem**
The previous version of socketIO is not working with python 2.7
Gazu isn't working with python 3.4
**Solution**
Use a correct version of python-socketio to work with python 2.7 and Zou : [documentation](https://python-socketio.readthedocs.io/en/latest/intro.html)
Drop support for python 3.4

SocketIO + python 3.4

---

README.rst

**Problem**
No downloads count for pip badge in the readme.rst
**Solution**
Add a download badge

[qa] add downloads count on pip badge

---

gazu/task.py

**Problem**
Users want to be able to not trigger normalization on the server side when uploading previews.
**Solution**
Add a flag to tell the server to not normalize the movies when uploading files. We assume there that users know what they are doing.

[previews] Allow to ask to the server to not normalize previews

---

gazu/files.py

**Problem**
No possibility to directly get the preview file URL
**Solution**
Create a new function (gazu.files.get_preview_file_url) to get this URL

[files] new function to get preview file url

---

gazu/casting.py

**Problem**
There is a slight misconception in a gazu function which retrieves all the entities where an asset is cast in. The function says thoses entities are only shots when it can be shots and assets
**Solution**
Changed the doc

Fix misconception in casting doc

---

.pre-commit-config.yaml
gazu/task.py
gazu/user.py
setup.cfg
setup.py
tests/test_task.py
tests/test_user.py

**Problem**
- in setup.py python_requires needs to accept python2.7 
- pre-commit and black don't work
- we need a function for user to get all done tasks 
- we need a function to get all tasks statuses for a project 
**Solution**
- fix setup.py to accept python>=2.7
- fix and update pre-commit and black
- add new function gazu.user.all_tasks_done + tests (https://github.com/cgwire/gazu/issues/224)
- add new function gazu.task.all_task_statuses_for_project  + tests (https://github.com/cgwire/gazu/issues/217)

various commits

---

tests/test_task.py

**Problem**
* AttributeError : module 'gazu.task' has no attribute 'add_attachment_to_comment'
**Solution**
* It's gazu.task.add_attachment_files_to_comment

[qa] fix test error

---

gazu/task.py

**Problem**
Gazu was missing the ability to update a task's comment
**Solution**
Added update_comment function to the task module

added task.update_comment

---

gazu/task.py
tests/test_task.py

**Problem**
calling task.remove_comment was failing with a NotAllowedException. After a little digging, I noticed the path needed the task context: 'data/tasks/%s/comments/%s' rather than 'data/comments/%s'. 
**Solution**
Updated task.remove_comment to include the task context.
I had the change the function signature to include a task parameter. 
I also updated the associated task_test

added task context to remove comment

---

gazu/asset.py
tests/test_asset.py

fixes #259
**Problem**
Project ID did not normalize when a uuid string was supplied to `gazu.asset.all_asset_types_for_project`.
**Solution**
Adds the `normalize_model_parameter` call like in similar functions.

all_asset_types_for_project normalize id fix.

---

gazu/project.py
setup.cfg
tests/test_asset.py
tests/test_project.py

**Problem**
- python 3.10 badge not shown in Pypi
- tests/test_asset.py needs to be refactored
- missing function to get team of a project
**Solution**
- show python 3.10 badge in python
- tests/test_asset.py is refactored
- add new function gazu.project.get_team

various fixes

---

gazu/person.py
tests/test_person.py

**Problem**
We needed to get the full person information.
**Solution**
Add an optional `relations` parameter to `gazu.person.get_person`.
This PR follows [this one](https://github.com/cgwire/zou/pull/584).

feat: add relations parameter to gazu.person.get_person

---

gazu/__init__.py
tests/test_client.py

**Problem**
- There's no parameters to log_in for 2FA
- There's no function to send an otp by email
**Solution**
- Add parameters to log_in for 2FA
- Add a function to send an otp by email

[2FA] add parameters to log_in for 2FA + add send_email_otp

---

docs/source/conf.py

**Problem**
- The search in documentation doesn't work, due to jQuery messing.
eg. https://gazu.cg-wire.com/search.html?q=test
**Solution**
- fix sphinx-rtd-theme install
**jQuery** is no longer included on **Sphinx** >= 6.x, but embedded by **sphinx-rtd-theme** >= 1.2.0
Learn more:
- https://sphinx-rtd-theme.readthedocs.io/en/stable/changelog.html#known-issues
- https://blog.readthedocs.com/sphinx6-upgrade/

Fix search due to missing jQuery

---

gazu/edit.py

**Problem**
- Cannot access edit tasks from gazu API
- Cannot check how many preview files already exist for a given edit
**Solution**
- Add a Function to Retrieve All Edits that Include Tasks
- Add Function to Retrieve all Tasks for a Given Edit
- Add Function to get all previews for an edit (useful for checking how many preview file revisions exist)

[edit] Add functions to retireve edit tasks & preview files

---

.github/workflows/ci.yml
.github/workflows/release.yml

**Problem**
We need a PyPi token on workstations to push on it.
Travis is slow to have feedback.
**Solution**
Use GitHub actions to run CI and made release.

Add Github actions to test and release

---

gazu/task.py

**Problem**
The revision number was sent to the tracker while a dict was expected, causing an not iterable error.
**Solution**
I updated the line to use data instead revision variable.

fix bug: use revision in dict

---

gazu/files.py
gazu/person.py
tests/test_files.py

**Problem**
There is no function to retrieve all output files for a given project.
**Solution**
Add `all_output_files_for_project` function.

Add all output files for projects

---

gazu/files.py
tests/test_files.py

**Problem**
- There's no function to delete a preview file. 
**Solution**
- Add new function gazu.files.remove_preview_file

[files] add new function gazu.files.remove_preview_file

---

gazu/__init__.py
gazu/person.py

**Problem**
- There's no way to use tokens for bots in Gazu.
**Solution**
- Add new function gazu.set_token to use these tokens for bots.

[bot] add new function set_token

---

examples/events.py
gazu/asset.py
gazu/concept.py
gazu/edit.py
gazu/entity.py
gazu/person.py
gazu/project.py
gazu/shot.py
gazu/task.py
tests/test_asset.py
tests/test_person.py

**Problem**
- Functions for creating / updating / deleting persons and bots need to be separated.
- The example for events can be improved.
- The route for creating a new person have been changed. 
**Solution**
- Functions for creating / updating / deleting persons and bots are now separated.
- The example for events is improved.
- Use the new route for creating a new person POST /data/persons.

various improvements : persons / bots

---

gazu/files.py
tests/test_files.py

**Problem**
There's no functions to upload avatars/thumbnails for projects and persons.
**Solution**
Add two functions:
- gazu.files.upload_project_avatar
- gazu.files.upload_person_avatar

[files] add functions to upload avatar for projects and persons

---

gazu/sync.py
tests/test_sync.py

**Problem**
For some sync cases, allow to build a model map based on another field than the ID (on the name in most cases).
**Solution**
Build the model map with the field given in the parameters.

[sync] Allow to build model map on any field

---

gazu/shot.py

**Problem**
While I try to update shot metadata, I often run into this error : 
AttributeError: 'NoneType' object has no attribute 'update'
Indeed it appears that sometimes my "current_shot" data looks like : {"id": "one_id", "data" : None }
**Solution**
Make sure that current_shot["data"] is not None before we call update()

handle meta update when key is present but its value is None

---

gazu/person.py
tests/test_person.py

**Problem**
There was no way to create a department from Gazu, neither looking for one by name
**Solution**
Added 2 functions to enable developers to create departments from Gazu and to search a department by name

[person/department] new func to add department or get one by name

---

gazu/task.py
tests/test_task.py

**Problem**
* Creating a new task type that already exists lead to an error
**Solution**
* Allow the function to search for existing task types like other functions

Check task type exists before creating it

---

gazu/exception.py

**Problem**
Projects may not exist when we need to use `gazu.get_task_by_entity()` so we need to handle these exceptions when we raise some errors.
**Solution**
Added some exceptions to handle this when it returns None.

Added some exceptions for some usages

---

gazu/sync.py
gazu/task.py

**Problem**
It's not possible to get tasks for a given task type, project and episode.
**Solution**
Modify existing functions to support project and episode filters.

Add more filters to retrieve episode tasks

---

gazu/client.py
tests/test_client.py
tests/test_files.py

**Problem**
Zou returns json objects with the 'error' key instead of 'message'. 
As an example; See https://github.com/cgwire/zou/blob/7f217f6be8cbc6eb1b10d80ca465c823b0aede40/zou/app/blueprints/files/resources.py#L705
**Solution**
I've added a utility function that checks a given request for the presence of both 'message' and 'error' keys, so that the error message of Zou can be properly passed on.
I also updated the UnitTests to test the following scenario's: verifying that the error message raised matches the one given by Zou and properly handling the error message when attempting to create a duplicate working file.

[Bugfix] Eror messages from Zou would not be returned properly

---

gazu/client.py

**Problem**
Previous pull request included type hinting, which is only supported with Python 3.6 onwards.
**Solution**
Removed type hinting to support Python 2.7.

Removed type hinting to support Python 2.7

---

netlify.toml

**Problem**
- We can set python runtime for building doc in netlify. 
**Solution**
- Set python 3.12

[runtime][netlify] set python 3.12 for netlify as runtime

---

.github/workflows/ci.yml
setup.cfg
tests/utils.py

**Problem**
- We don't support and have a CI for python 3.13.
**Solution**
- Add support for python 3.13 + fix relative issues.

Add support for Python 3.13

---

.gitignore
gazu/client.py

**Problem**
Zou has the ability to provide pagination, but Gazu ignores this functionality at the moment.
I used the get_preview_files_for_project method exposed at the /data/preview-files webhook to fetch all preview files, it becomes impossible to fetch these records. Zou yields a 502 Gateway Error. I am aware that this is an absurd query, but it's a good benchmark.
Pagination is available in Zou: https://github.com/cgwire/zou/blob/8be5dfd1744115ec08eb0c5668db62e1854ebbed/zou/app/services/files_service.py#L902
**Solution**
I added the "pagination" parameter to "fetch_all", which will cause the method to handle the query in slices of 100.
`gazu.client.fetch_all('preview-files',` params=project_id, paginated=True)`
This solution also works for Persons, Tasks and other resources that …

Added pagination to fetch_all method

---

.github/workflows/ci.yml
.github/workflows/release.yml
gazu/person.py
gazu/project.py
gazu/task.py
tests/test_person.py

**Problem**
- For time_spent docs duration is in seconds meanwhile it's in minutes. 
- Some github actions are outdated. 
- gazu.project.get_project_url doesn't use the client.
- for gazu.person.get_person relations param needs to be set to true (it's by default to false on api side). 
**Solution**
- For time_spent docs duration is in minutes now. 
- Update some github actions. 
- gazu.project.get_project_url now use the client.
- for gazu.person.get_person set param "relations" to True.

various improvements 

---

gazu/task.py
tests/test_task.py

**Problem**
- No method for getting task type by short name. 
**Solution**
- Add new function task.get_task_type_by_short_name.

[task] add new function task.get_task_type_by_short_name

---

gazu/user.py

**Problem**
The url was missing a plural.
**Solution**
Use the correct url.
[Zou blueprint](https://github.com/cgwire/zou/blob/a8e89d6381c2260664f9e4d798c96d7f91ea9546/zou/app/blueprints/user/__init__.py#L54)

fix(user.py): Use the right url path to access to scenes tasks
